spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_user
    username: postgres
    password: master123
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081